---
title: "Assignment 3, Task 2"
author: "Catherine Takata"
date: "2/24/2021"
output: 
  html_document:
    theme: cerulean
    code_folding: show
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster) 
library(tidyverse)
library(here)
library(sf)
library(fasterize)
library(rnaturalearth)
```

```{r}
ca_species <- list.files(path = here("ca_cetaceans"), pattern = "*.tif", full.names = TRUE)
species_stack <- raster::stack(ca_species)
```

```{r}
cetaceans_thresh <- function(x, thresh = .6) {
  y <- ifelse(x >= thresh, 1, NA)
  return(y)
}

species_richness <- calc(species_stack, fun = cetaceans_thresh)

species_richness_sum <- calc(species_richness, fun = sum, na.rm = TRUE)
```

## Convert to a dataframe
`ggplot` likes dataframes - not rasters - so we have to convert our raster to a dataframe.  The `raster::rasterToPoints()` function converts a raster to a matrix of points - `x`, `y`, and `layer` (or the layer name if it's a named layer).  Then `as.data.frame()` can convert that matrix to a `data.frame` object suitable for `ggplot.`

```{r}
species_richness_df <- raster::rasterToPoints(species_richness) %>%
  as.data.frame()
species_sum_df <- raster::rasterToPoints(species_richness_sum) %>%
  as.data.frame()
```


```{r}
coastline <- ne_download(scale = 110, type = 'coastline', category = 'physical', returnclass = "sf")

ggplot() + 
  geom_raster(data = species_sum_df, aes(x = x, y = y, fill = layer)) +
  geom_sf(data = coastline) +
  coord_sf(xlim = c(-125, -115), ylim = c(32, 38)) + 
  scale_fill_gradient(low = 'white', high = 'blue') +
  theme_void() 
  #theme(panel.background = element_rect(fill = 'slateblue'))
```



